/**
 * Version information for the Jeopardy Pro application
 * This file is auto-generated by scripts/sync-version.js
 */

export interface VersionInfo {
  version: string;
  buildMetadata: string;
  fullVersion: string;
  buildDate: string;
  gitSha: string;
  gitBranch: string;
}

let versionData: VersionInfo | null = null;

try {
  // @ts-ignore - version.json is generated at build time
  versionData = await import('./version.json');
} catch (error) {
  // Fallback if version.json doesn't exist
  versionData = {
    version: '2.0.0',
    buildMetadata: '',
    fullVersion: '2.0.0',
    buildDate: new Date().toISOString(),
    gitSha: 'unknown',
    gitBranch: 'unknown'
  };
}

export const version = versionData;
